//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularVize.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TKayit
    {
        public string kayitId { get; set; }
        public string kayitDersId { get; set; }
        public string kayitOgrId { get; set; }
        public string kayitOgrtId { get; set; }
    
        public virtual TDersler TDersler { get; set; }
        public virtual TOgrenci TOgrenci { get; set; }
        public virtual TOgretmen TOgretmen { get; set; }
    }
}
