//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularVize.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TKullanici
    {
        public string kulId { get; set; }
        public string kulAdi { get; set; }
        public string kulSifre { get; set; }
        public string kulYetki { get; set; }
        public string kulOgrId { get; set; }
    
        public virtual TOgrenci TOgrenci { get; set; }
        public virtual TOgrenci TOgrenci1 { get; set; }
    }
}
